### ISSUE TITLE
Unable to specify Athena workgroup

### ISSUE THREAD

**Issue by james-lukensow** [aws-samples/aws-cudos-framework-deployment#113]
When deploying the cudos framework, I'm unable to specify the "workgroup".

Is it possible to select a workgroup other than "primary"?

Usecase: I'm manually deploying the Cudos CloudFormation template and it appears it always selects "primary" as the default workgroup.

**Comment by darken99** [comment]
What is the use case for using workgroup other than "primary" ?

**Comment by megareez** [comment]
Indeed as you might have noticed we do support the "Primary" workgroup by default. 
If there is a need any other workgroup the existing CFN can be modified by the end user to the required preference of the end user. 

We will take the workgroup parameter as a PFR for the CFN template.

**Comment by shreedharn-cbm** [comment]
Using a separate workgroup provides greater flexility in terms of preserving distinct query history, enforcing cost constraints and policies (see references below). CFN should have a workgroup parameter so that the user have a choice to use either primary or any other workgroup. Given that workgroups are associated with result buckets, a separate parameter may not be required for results bucket. In summary, ability to provide Workgroup provides greater flexibility/control than just providing results bucket.
 
Reference: 
https://docs.aws.amazon.com/athena/latest/ug/workgroups-benefits.html
https://docs.aws.amazon.com/athena/latest/ug/example-policies-workgroup.html
